exception: Remove duplicate definition of macro `ThrowFileException'
The definition in `MagickWand/convert.c' has been deleted; it was
identical to the definition in `MagickCore/exception-private.h',
a header which is now included instead.